export const CLEAR_RESERVATIONS = "CLEAR_RESERVATIONS";
export const SAVE_RESERVATIONS = "SAVE_RESERVATIONS";

export const DELETE_USER = "CLEAR_RESERVATIONS";
export const SAVE_USER = "SAVE_RESERVATIONS";