export const CLEAR_RESERVATIONS = "CLEAR_RESERVATIONS";
export const SAVE_RESERVATIONS = "SAVE_RESERVATIONS";

export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const CLEAN = "SAVE_RESERVATIONS";